<?php

return array (
    0 =>
        array (
            'id' => 1,
            'type' => 'file',
            'pid' => 0,
            'name' => 'dashboard',
            'title' => '控制台',
            'icon' => 'fa fa-dashboard',
            'condition' => '',
            'remark' => 'Dashboard tips',
            'ismenu' => 1,
            'createtime' => '2019-06-14 16:45:20',
            'updatetime' => '2019-06-14 22:45:50',
            'weigh' => 143,
            'status' => 'normal',
        ),
    1 =>
        array (
            'id' => 2,
            'type' => 'file',
            'pid' => 0,
            'name' => 'cloud',
            'title' => '云端平台',
            'icon' => 'fa fa-cloud',
            'condition' => '',
            'remark' => 'Cloud tips',
            'ismenu' => 1,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    2 =>
        array (
            'id' => 3,
            'type' => 'file',
            'pid' => 1,
            'name' => 'dashboard/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-06-14 16:45:20',
            'updatetime' => '2019-06-14 16:45:20',
            'weigh' => 136,
            'status' => 'normal',
        ),
    3 =>
        array (
            'id' => 4,
            'type' => 'file',
            'pid' => 3,
            'name' => 'dashboard/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-06-14 16:45:20',
            'updatetime' => '2019-06-14 16:45:20',
            'weigh' => 135,
            'status' => 'normal',
        ),
    4 =>
        array (
            'id' => 5,
            'type' => 'file',
            'pid' => 3,
            'name' => 'dashboard/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-06-14 16:45:20',
            'updatetime' => '2019-06-14 16:45:20',
            'weigh' => 133,
            'status' => 'normal',
        ),
    5 =>
        array (
            'id' => 6,
            'type' => 'file',
            'pid' => 3,
            'name' => 'dashboard/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-06-14 16:45:20',
            'updatetime' => '2019-06-14 16:45:20',
            'weigh' => 134,
            'status' => 'normal',
        ),
    6 =>
        array (
            'id' => 7,
            'type' => 'file',
            'pid' => 3,
            'name' => 'dashboard/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-06-14 16:45:20',
            'updatetime' => '2019-06-14 16:45:20',
            'weigh' => 132,
            'status' => 'normal',
        ),
    7 =>
        array (
            'id' => 8,
            'type' => 'file',
            'pid' => 2,
            'name' => 'addon/index',
            'title' => 'Addon market',
            'icon' => 'fa fa-puzzle-piece',
            'condition' => '',
            'remark' => 'Addon tips',
            'ismenu' => 1,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    8 =>
        array (
            'id' => 9,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    9 =>
        array (
            'id' => 10,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    10 =>
        array (
            'id' => 11,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    11 =>
        array (
            'id' => 12,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/local',
            'title' => '本地安装',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    12 =>
        array (
            'id' => 13,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/state',
            'title' => '禁用启用',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    13 =>
        array (
            'id' => 14,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/install',
            'title' => '安装',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    14 =>
        array (
            'id' => 15,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/uninstall',
            'title' => '卸载',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    15 =>
        array (
            'id' => 16,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/config',
            'title' => '配置',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    16 =>
        array (
            'id' => 17,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/refresh',
            'title' => '刷新',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    17 =>
        array (
            'id' => 18,
            'type' => 'file',
            'pid' => 8,
            'name' => 'addon/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
    18 =>
        array (
            'id' => 19,
            'type' => 'file',
            'pid' => 2,
            'name' => 'vendor/index',
            'title' => 'Vendor market',
            'icon' => 'fa fa-cloud-download',
            'condition' => '',
            'remark' => 'Vendor tips',
            'ismenu' => 1,
            'createtime' => '2019-08-07 00:05:09',
            'updatetime' => '2019-08-07 00:05:09',
            'weigh' => 0,
            'status' => 'normal',
        ),
);